#!/usr/bin/env python3
"""Deterministic synthetic dataset + squared-error gradient-boosting trace for
Exercise 7's "Build a Boosted Model" activity (WP32).

The dataset is entirely synthetic -- 24 observations on one continuous
predictor and a noisy, smooth nonlinear target, generated by one fixed
formula with a seed decided before generation (unlike Exercise 6's greedy-
split activity, no split-optimum "niceness" search applies here, since this
activity never asks a student to find an optimal split)::

    x ~ Uniform(X_LOW, X_HIGH)
    y = C + A*sin(FREQ*x) + B*x + noise
    noise ~ Normal(0, NOISE_SD)

For each learning rate in ``LEARNING_RATES``, this script recomputes, for
every stage 0..N_STAGES:

* stage 0 -- the ensemble prediction is the training-target mean for every
  observation (no tree yet);
* stage m>0 -- a shallow regression stump (``max_depth=1``) is fit to the
  residuals ``r_i = y_i - yhat_i^(m-1)`` left by the previous stage; the new
  ensemble prediction is ``yhat_i^(m-1) + eta * f_m(x_i)``, following exactly
  Exercise 7's declared update equation.

The output, ``book/_static/widgets/data/boosting_step_by_step.json``, is both
the browser widget's data artifact and this activity's committed
deterministic audit.

Usage::

    python scripts/export_boosting_step_widget.py --refresh   # writes JSON
    python scripts/export_boosting_step_widget.py --check     # re-validate

Asserted by ``tests/test_export_boosting_step_widget_data.py``.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "book" / "_static" / "widgets" / "data" / "boosting_step_by_step.json"
MANIFEST_PATH = REPO_ROOT / "book" / "config" / "abide_modeling.json"

sys.path.insert(0, str(Path(__file__).resolve().parent))

from semantic_json_compare import DEFAULT_ABS_TOL, semantic_diff  # noqa: E402

_MANIFEST = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
_STEP = _MANIFEST["gradient_boosting"]["step_by_step"]

N_OBSERVATIONS = _STEP["n_observations"]
SEED = _STEP["seed"]
X_LOW = _STEP["x_distribution"]["low"]
X_HIGH = _STEP["x_distribution"]["high"]
C = _STEP["coefficients"]["C"]
A = _STEP["coefficients"]["A"]
FREQ = _STEP["coefficients"]["FREQ"]
B = _STEP["coefficients"]["B"]
NOISE_SD = _STEP["coefficients"]["NOISE_SD"]
LEARNING_RATES: list[float] = _STEP["learning_rates"]
N_STAGES: int = _STEP["n_stages"]
STUMP_MAX_DEPTH: int = _STEP["stump_settings"]["max_depth"]


def _generate() -> tuple[list[float], list[float]]:
    import numpy as np

    rng = np.random.RandomState(SEED)
    x = rng.uniform(X_LOW, X_HIGH, size=N_OBSERVATIONS)
    noise = rng.normal(0.0, NOISE_SD, size=N_OBSERVATIONS)
    y = C + A * np.sin(FREQ * x) + B * x + noise
    return [round(float(v), 4) for v in x], [round(float(v), 3) for v in y]


def build_observations() -> list[dict[str, Any]]:
    x, y = _generate()
    order = sorted(range(N_OBSERVATIONS), key=lambda i: x[i])
    return [{"id": i, "x": x[j], "y": y[j]} for i, j in enumerate(order)]


def _stump_fit(x: Any, residual: Any) -> dict[str, Any]:
    from sklearn.tree import DecisionTreeRegressor

    stump = DecisionTreeRegressor(max_depth=STUMP_MAX_DEPTH, random_state=0)
    stump.fit(x.reshape(-1, 1), residual)
    prediction = stump.predict(x.reshape(-1, 1))
    tree = stump.tree_
    threshold = round(float(tree.threshold[0]), 4)
    left_value = round(float(tree.value[tree.children_left[0]][0][0]), 4)
    right_value = round(float(tree.value[tree.children_right[0]][0][0]), 4)
    return {
        "threshold": threshold,
        "leftValue": left_value,
        "rightValue": right_value,
        "prediction": prediction,
    }


def build_stages_for_rate(x: Any, y: Any, eta: float) -> list[dict[str, Any]]:
    import numpy as np

    mean_y = float(np.mean(y))
    ensemble = np.full(N_OBSERVATIONS, mean_y, dtype="float64")
    stages: list[dict[str, Any]] = []
    residual0 = y - ensemble
    stages.append(
        {
            "stage": 0,
            "ensemblePrediction": [round(float(v), 4) for v in ensemble],
            "residualBeforeUpdate": [round(float(v), 4) for v in residual0],
            "trainMSE": round(float(np.mean(residual0**2)), 4),
            "stump": None,
            "treePrediction": None,
            "scaledCorrection": None,
        }
    )
    for m in range(1, N_STAGES + 1):
        residual_before = y - ensemble
        fit = _stump_fit(x, residual_before)
        raw = fit["prediction"]
        scaled = eta * raw
        ensemble = ensemble + scaled
        stages.append(
            {
                "stage": m,
                "ensemblePrediction": [round(float(v), 4) for v in ensemble],
                "residualBeforeUpdate": [round(float(v), 4) for v in residual_before],
                "trainMSE": round(float(np.mean((y - ensemble) ** 2)), 4),
                "stump": {
                    "threshold": fit["threshold"],
                    "leftValue": fit["leftValue"],
                    "rightValue": fit["rightValue"],
                },
                "treePrediction": [round(float(v), 4) for v in raw],
                "scaledCorrection": [round(float(v), 4) for v in scaled],
            }
        )
    return stages


def build_data() -> dict[str, Any]:
    import numpy as np

    observations = build_observations()
    x = np.array([o["x"] for o in observations], dtype="float64")
    y = np.array([o["y"] for o in observations], dtype="float64")

    stages_by_rate = {str(eta): build_stages_for_rate(x, y, eta) for eta in LEARNING_RATES}

    return {
        "schemaVersion": 1,
        "activity": "boosting-step-by-step",
        "syntheticDataNote": (
            "This dataset is simulated: one continuous predictor and a noisy, smooth nonlinear "
            "target, generated from a fixed formula and seed. It is used to walk through squared-"
            "error gradient boosting one shallow tree at a time -- these are not ABIDE observations."
        ),
        "generatingProcess": {
            "formula": "y = C + A*sin(FREQ*x) + B*x + noise, noise ~ Normal(0, NOISE_SD)",
            "x": {"distribution": "Uniform", "low": X_LOW, "high": X_HIGH},
            "coefficients": {"C": C, "A": A, "FREQ": FREQ, "B": B, "noiseSD": NOISE_SD},
            "nObservations": N_OBSERVATIONS,
            "seed": SEED,
            "seedNote": "Fixed before generation; no seed search (unlike the Exercise 6 greedy-split activity).",
        },
        "feature": {"name": "x", "label": "Predictor (x)"},
        "target": {"name": "y", "label": "Target (y)"},
        "observations": observations,
        "learningRates": LEARNING_RATES,
        "nStages": N_STAGES,
        "stumpSettings": {"maxDepth": STUMP_MAX_DEPTH},
        "updateEquation": "yhat_i^(m) = yhat_i^(m-1) + eta * f_m(x_i)",
        "stagesByLearningRate": stages_by_rate,
    }


def serialize(obj: dict[str, Any]) -> str:
    return json.dumps(obj, ensure_ascii=False, sort_keys=True, indent=2) + "\n"


def cmd_refresh() -> int:
    data = build_data()
    text = serialize(data)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)} ({len(text.encode())} bytes)")
    _print_summary(data)
    return 0


def validate(data: dict[str, Any]) -> list[str]:
    problems: list[str] = []
    if len(data.get("observations", [])) != N_OBSERVATIONS:
        problems.append(f"observations count must be exactly {N_OBSERVATIONS}")
    gp = data.get("generatingProcess", {})
    if gp.get("seed") != SEED:
        problems.append(f"generatingProcess.seed must be {SEED}")

    stages_by_rate = data.get("stagesByLearningRate", {})
    for eta in LEARNING_RATES:
        stages = stages_by_rate.get(str(eta))
        if stages is None:
            problems.append(f"missing stages for learning rate {eta}")
            continue
        if len(stages) != N_STAGES + 1:
            problems.append(f"learning rate {eta}: expected {N_STAGES + 1} stages (0..{N_STAGES})")
            continue
        stage0 = stages[0]
        mean_y = round(sum(o["y"] for o in data["observations"]) / N_OBSERVATIONS, 4)
        if any(abs(v - mean_y) > 1e-3 for v in stage0["ensemblePrediction"]):
            problems.append(f"learning rate {eta}: stage 0 must equal the training-target mean for every observation")
        if stage0["stump"] is not None:
            problems.append(f"learning rate {eta}: stage 0 must not have a stump")

        for m in range(1, len(stages)):
            prev = stages[m - 1]["ensemblePrediction"]
            cur = stages[m]
            scaled = cur["scaledCorrection"]
            if scaled is None or cur["treePrediction"] is None:
                problems.append(f"learning rate {eta} stage {m}: missing treePrediction/scaledCorrection")
                continue
            recomputed = [round(p + s, 4) for p, s in zip(prev, scaled)]
            for i, (rec, stored) in enumerate(zip(recomputed, cur["ensemblePrediction"])):
                if abs(rec - stored) > 1e-2:
                    problems.append(
                        f"learning rate {eta} stage {m} obs {i}: ensemble prediction does not follow "
                        f"yhat^(m) = yhat^(m-1) + eta*f_m(x) (recomputed {rec}, stored {stored})"
                    )
                    break
            expected_scaled = [round(eta * t, 4) for t in cur["treePrediction"]]
            if any(abs(a - b) > 1e-3 for a, b in zip(expected_scaled, scaled)):
                problems.append(f"learning rate {eta} stage {m}: scaledCorrection does not equal eta*treePrediction")

        # Training MSE should generally decrease as trees are added; softly
        # check the last stage is not worse than stage 0 by a wide margin.
        if stages[-1]["trainMSE"] > stages[0]["trainMSE"]:
            problems.append(f"learning rate {eta}: final-stage training MSE is worse than stage 0's")

    return problems


def cmd_check() -> int:
    if not OUT_PATH.exists():
        print(f"ERROR: {OUT_PATH} missing; run --refresh first.", file=sys.stderr)
        return 1
    data = json.loads(OUT_PATH.read_text(encoding="utf-8"))
    recomputed = build_data()
    mismatch = semantic_diff(data, recomputed, abs_tol=DEFAULT_ABS_TOL)
    if mismatch is not None:
        print("ERROR: committed artifact does not match a fresh recomputation.", file=sys.stderr)
        print(f"  - {mismatch}", file=sys.stderr)
        return 1
    problems = validate(data)
    if problems:
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1
    print(f"OK: {OUT_PATH.relative_to(REPO_ROOT)} is self-consistent.")
    _print_summary(data)
    return 0


def _print_summary(data: dict[str, Any]) -> None:
    for eta in LEARNING_RATES:
        stages = data["stagesByLearningRate"][str(eta)]
        print(f"eta={eta:<4} stage0 MSE={stages[0]['trainMSE']:.2f}  stage{N_STAGES} MSE={stages[-1]['trainMSE']:.2f}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--refresh", action="store_true", help="recompute and write the JSON artifact")
    mode.add_argument("--check", action="store_true", help="re-validate the committed JSON artifact (offline)")
    args = parser.parse_args(argv)
    return cmd_refresh() if args.refresh else cmd_check()


if __name__ == "__main__":
    raise SystemExit(main())
