#!/usr/bin/env python3
"""Deterministic synthetic dataset + greedy-split audit for Exercise 6's
"Build a Tree Greedily" activity (WP30, replacing WP29's four-quadrant
version end-to-end).

The dataset is entirely synthetic -- 16 observations on two continuous,
normally distributed predictors ("Brain measure 1" / "Brain measure 2") and
a noisy continuous target, generated by one fixed formula::

    x1 ~ Normal(MU1, SD1)
    x2 ~ Normal(MU2, SD2)
    y = INTERCEPT + BETA1*z(x1) + BETA2*z(x2) + GAMMA*z(x1)*z(x2) + noise
    noise ~ Normal(0, NOISE_SD)
    z(x) = (x - mean) / sd            (population parameters, not sample)

Unlike WP29's artificial four-"quadrant" points, this dataset's two
features visibly overlap in feature space and neither one determines the
target on its own -- while still giving three clean, learnable splitting
rounds. The formula's coefficients, standard deviations, and noise level are
fixed *before* any seed is inspected (WP30 sec 3.1); seeds ``0..49`` are then
tried in order, and the first seed meeting every predeclared numerical
acceptance criterion in :func:`seed_diagnostics` is used -- not the seed
with the largest MSE reduction. Seed 17 is the first (and only, among
0..49) seed that passes. See ``WPs/reports/WP30_REPORT.md`` for the full
per-seed and per-round audit.

This script recomputes, for every round (root / left child / right child):

* the active observations;
* every valid candidate threshold for each feature (the midpoints between
  that feature's distinct observed values among the active observations);
* the weighted split MSE and MSE reduction at every candidate threshold;
* the optimal feature, threshold, split MSE, and reduction.

The output, ``book/_static/widgets/data/tree_greedy_split.json``, is both
the browser widget's data artifact and this activity's committed
deterministic audit (there is no separate ABIDE-style audit script for a
synthetic dataset with no model-fitting decisions to record).

Usage::

    python scripts/export_tree_greedy_widget.py --refresh   # writes JSON
    python scripts/export_tree_greedy_widget.py --check     # re-validate

Asserted by ``tests/test_export_tree_greedy_widget_data.py``.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "book" / "_static" / "widgets" / "data" / "tree_greedy_split.json"

# --- the fixed generating formula (decided before any seed was inspected) --
N_OBSERVATIONS = 16
MU1, SD1 = 5.5, 2.0
MU2, SD2 = 5.5, 2.0
INTERCEPT = 20.0
BETA1 = 6.0
BETA2 = 5.0
GAMMA = 1.5  # modest interaction term
NOISE_SD = 2.5
SEED_SEARCH_RANGE = range(50)  # inspected in order; first pass wins
SELECTED_SEED = 17


def _generate_raw(seed: int) -> tuple[list[float], list[float], list[float]]:
    import numpy as np

    rng = np.random.RandomState(seed)
    x1 = rng.normal(MU1, SD1, size=N_OBSERVATIONS)
    x2 = rng.normal(MU2, SD2, size=N_OBSERVATIONS)
    noise = rng.normal(0.0, NOISE_SD, size=N_OBSERVATIONS)
    z1 = (x1 - MU1) / SD1
    z2 = (x2 - MU2) / SD2
    y = INTERCEPT + BETA1 * z1 + BETA2 * z2 + GAMMA * z1 * z2 + noise
    x1 = [round(float(v), 3) for v in x1]
    x2 = [round(float(v), 3) for v in x2]
    y = [round(float(v), 2) for v in y]
    return x1, x2, y


def build_observations(seed: int = SELECTED_SEED) -> list[dict[str, Any]]:
    x1, x2, y = _generate_raw(seed)
    return [{"id": i, "x1": x1[i], "x2": x2[i], "y": y[i]} for i in range(N_OBSERVATIONS)]


def _best_and_second(active: list[dict[str, Any]]) -> tuple[dict[str, Any], dict[str, Any], float]:
    """The best and second-best candidate split across both features, by
    reduction, plus the parent MSE -- used by both the seed-acceptance
    criteria and the report's runner-up numbers."""
    parent_mse = round(_mse([o["y"] for o in active]), 6)
    candidates: list[dict[str, Any]] = []
    for feature in ("x1", "x2"):
        c = _feature_candidates(active, feature)
        for i, t in enumerate(c["thresholds"]):
            candidates.append(
                {
                    "feature": feature,
                    "threshold": t,
                    "splitMSE": c["splitMSE"][i],
                    "reduction": c["reduction"][i],
                    "nLeft": c["nLeft"][i],
                    "nRight": c["nRight"][i],
                }
            )
    candidates.sort(key=lambda c: -c["reduction"])
    return candidates[0], candidates[1], parent_mse


def seed_diagnostics(seed: int) -> tuple[bool, list[str]]:
    """Predeclared numerical acceptance criteria (WP30 sec 3.1), fixed
    before any seed's dataset was inspected. Returns (passed, reasons)."""
    import numpy as np

    observations = build_observations(seed)
    x1 = np.array([o["x1"] for o in observations])
    x2 = np.array([o["x2"] for o in observations])
    y = np.array([o["y"] for o in observations])
    reasons: list[str] = []

    corr1 = float(np.corrcoef(x1, y)[0, 1])
    corr2 = float(np.corrcoef(x2, y)[0, 1])
    corr_cross = float(np.corrcoef(x1, x2)[0, 1])
    if not (0.35 <= abs(corr1) <= 0.90):
        reasons.append(f"corr(x1,y)={corr1:.3f} outside [0.35, 0.90]")
    if not (0.35 <= abs(corr2) <= 0.90):
        reasons.append(f"corr(x2,y)={corr2:.3f} outside [0.35, 0.90]")
    if abs(corr_cross) > 0.40:
        reasons.append(f"corr(x1,x2)={corr_cross:.3f} exceeds 0.40 (too collinear)")

    best, second, _ = _best_and_second(observations)
    margin = best["reduction"] - second["reduction"]
    ratio = margin / best["reduction"] if best["reduction"] > 0 else 0.0
    if margin <= 0.75:
        reasons.append(f"root margin {margin:.3f} <= 0.75 (not a clear unique optimum)")
    if ratio > 0.55:
        reasons.append(f"root margin ratio {ratio:.3f} > 0.55 (optimum too visually obvious)")
    if best["nLeft"] < 5 or best["nRight"] < 5:
        reasons.append(f"root split sizes {best['nLeft']}/{best['nRight']} below 5/5")

    root_feature, root_threshold = best["feature"], best["threshold"]
    left_active = [o for o in observations if o[root_feature] <= root_threshold]
    right_active = [o for o in observations if o[root_feature] > root_threshold]
    features_used = {root_feature}
    for name, active in (("left", left_active), ("right", right_active)):
        if len(active) < 6:
            reasons.append(f"{name} child has only {len(active)} observations (< 6)")
            continue
        cbest, csecond, _ = _best_and_second(active)
        cmargin = cbest["reduction"] - csecond["reduction"]
        cratio = cmargin / cbest["reduction"] if cbest["reduction"] > 0 else 0.0
        if cmargin <= 0.5:
            reasons.append(f"{name} child margin {cmargin:.3f} <= 0.5")
        if cratio > 0.60:
            reasons.append(f"{name} child margin ratio {cratio:.3f} > 0.60")
        if cbest["nLeft"] < 3 or cbest["nRight"] < 3:
            reasons.append(f"{name} child split sizes {cbest['nLeft']}/{cbest['nRight']} below 3/3")
        features_used.add(cbest["feature"])

    if features_used != {"x1", "x2"}:
        reasons.append(f"both features not used across the tree (used: {sorted(features_used)})")

    return len(reasons) == 0, reasons


def select_seed() -> int:
    """Scan seeds 0..49 in declaration order; return the first that passes
    every acceptance criterion. Raises if none does (WP30 sec 3.1: stop and
    report the blocker rather than continuing to search)."""
    for seed in SEED_SEARCH_RANGE:
        passed, _ = seed_diagnostics(seed)
        if passed:
            return seed
    raise RuntimeError(f"no seed in {SEED_SEARCH_RANGE} met the predeclared acceptance criteria")


def _mse(ys: list[float]) -> float:
    if not ys:
        return 0.0
    mean = sum(ys) / len(ys)
    return sum((v - mean) ** 2 for v in ys) / len(ys)


def _candidate_thresholds(values: list[float]) -> list[float]:
    uniq = sorted(set(values))
    return [round((uniq[i] + uniq[i + 1]) / 2, 4) for i in range(len(uniq) - 1)]


def _feature_candidates(active: list[dict[str, Any]], feature: str) -> dict[str, Any]:
    parent_mse = round(_mse([o["y"] for o in active]), 6)
    n = len(active)
    values = [o[feature] for o in active]
    thresholds = _candidate_thresholds(values)
    split_mse, reduction, n_left, n_right = [], [], [], []
    for t in thresholds:
        left = [o["y"] for o in active if o[feature] <= t]
        right = [o["y"] for o in active if o[feature] > t]
        wmse = (len(left) / n) * _mse(left) + (len(right) / n) * _mse(right)
        split_mse.append(round(wmse, 6))
        reduction.append(round(parent_mse - wmse, 6))
        n_left.append(len(left))
        n_right.append(len(right))
    return {
        "thresholds": thresholds,
        "splitMSE": split_mse,
        "reduction": reduction,
        "nLeft": n_left,
        "nRight": n_right,
    }


def _round_summary(round_id: str, label: str, active: list[dict[str, Any]]) -> dict[str, Any]:
    parent_mse = round(_mse([o["y"] for o in active]), 6)
    candidates = {"x1": _feature_candidates(active, "x1"), "x2": _feature_candidates(active, "x2")}

    best = None
    for feature in ("x1", "x2"):
        c = candidates[feature]
        for i, red in enumerate(c["reduction"]):
            if best is None or red > best["reduction"]:
                best = {
                    "feature": feature,
                    "thresholdIndex": i,
                    "threshold": c["thresholds"][i],
                    "splitMSE": c["splitMSE"][i],
                    "reduction": red,
                    "nLeft": c["nLeft"][i],
                    "nRight": c["nRight"][i],
                }
    assert best is not None
    left_ys = [o["y"] for o in active if o[best["feature"]] <= best["threshold"]]
    right_ys = [o["y"] for o in active if o[best["feature"]] > best["threshold"]]
    best["leftMean"] = round(sum(left_ys) / len(left_ys), 3)
    best["rightMean"] = round(sum(right_ys) / len(right_ys), 3)

    return {
        "id": round_id,
        "label": label,
        "activeObservationIds": [o["id"] for o in active],
        "parentMSE": parent_mse,
        "candidates": candidates,
        "optimal": best,
    }


def build_data() -> dict[str, Any]:
    observations = build_observations(SELECTED_SEED)

    root_active = observations
    root = _round_summary("root", "Root node (all 16 observations)", root_active)
    opt = root["optimal"]

    left_active = [o for o in root_active if o[opt["feature"]] <= opt["threshold"]]
    right_active = [o for o in root_active if o[opt["feature"]] > opt["threshold"]]
    left = _round_summary(
        "left-child",
        f"Left child ({opt['feature'].upper()} <= {opt['threshold']})",
        left_active,
    )
    right = _round_summary(
        "right-child",
        f"Right child ({opt['feature'].upper()} > {opt['threshold']})",
        right_active,
    )

    return {
        "schemaVersion": 1,
        "activity": "tree-greedy-split",
        "syntheticDataNote": (
            "This dataset is simulated: two continuous predictors and a noisy continuous "
            "target, generated from a fixed formula to have an understandable but not-too-easy "
            "split structure. It is used to understand the greedy-splitting algorithm -- these "
            "are not ABIDE observations."
        ),
        "generatingProcess": {
            "formula": "y = INTERCEPT + BETA1*z(x1) + BETA2*z(x2) + GAMMA*z(x1)*z(x2) + noise",
            "x1": {"distribution": "Normal", "mean": MU1, "sd": SD1},
            "x2": {"distribution": "Normal", "mean": MU2, "sd": SD2},
            "intercept": INTERCEPT,
            "beta1": BETA1,
            "beta2": BETA2,
            "gamma": GAMMA,
            "noiseSD": NOISE_SD,
            "nObservations": N_OBSERVATIONS,
            "seedSearchRange": [SEED_SEARCH_RANGE.start, SEED_SEARCH_RANGE.stop - 1],
            "selectedSeed": SELECTED_SEED,
            "selectionNote": (
                "Seeds were tried in order starting at 0; the first seed meeting every "
                "predeclared numerical acceptance criterion (see "
                "scripts/export_tree_greedy_widget.py:seed_diagnostics) was used."
            ),
        },
        "features": {
            "x1": {"name": "x1", "label": "Brain measure 1"},
            "x2": {"name": "x2", "label": "Brain measure 2"},
        },
        "observations": observations,
        "rounds": [root, left, right],
    }


def serialize(obj: dict[str, Any]) -> str:
    return json.dumps(obj, ensure_ascii=False, sort_keys=True, indent=2) + "\n"


def cmd_refresh() -> int:
    data = build_data()
    text = serialize(data)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)} ({len(text.encode())} bytes)")
    _print_summary(data)
    return 0


def validate(data: dict[str, Any]) -> list[str]:
    problems: list[str] = []
    if len(data.get("observations", [])) != N_OBSERVATIONS:
        problems.append(f"observations count must be exactly {N_OBSERVATIONS}")
    gp = data.get("generatingProcess", {})
    if gp.get("selectedSeed") != SELECTED_SEED:
        problems.append(f"generatingProcess.selectedSeed must be {SELECTED_SEED}")
    else:
        recomputed_seed = select_seed()
        if recomputed_seed != SELECTED_SEED:
            problems.append(
                f"a fresh scan of seeds {list(SEED_SEARCH_RANGE)} selects seed {recomputed_seed}, "
                f"not the committed {SELECTED_SEED}"
            )
        passed, reasons = seed_diagnostics(SELECTED_SEED)
        if not passed:
            problems.append(f"selected seed {SELECTED_SEED} fails its own acceptance criteria: {reasons}")
        for earlier_seed in range(SELECTED_SEED):
            earlier_passed, _ = seed_diagnostics(earlier_seed)
            if earlier_passed:
                problems.append(f"seed {earlier_seed} < {SELECTED_SEED} also passes; it should have been selected first")
    rounds = data.get("rounds", [])
    if len(rounds) != 3:
        problems.append("there must be exactly 3 rounds (root, left child, right child)")
    if rounds:
        if rounds[0]["optimal"]["feature"] != "x1":
            problems.append("root optimal split is expected to be on x1 for this dataset")
        for r in rounds[1:]:
            if r["optimal"]["feature"] != "x2":
                problems.append(f"round {r['id']}: optimal split is expected to be on x2 for this dataset")
        for r in rounds:
            for feature, c in r["candidates"].items():
                lengths = {len(c["thresholds"]), len(c["splitMSE"]), len(c["reduction"]), len(c["nLeft"]), len(c["nRight"])}
                if len(lengths) != 1:
                    problems.append(f"round {r['id']} feature {feature}: candidate array length mismatch")
                opt = r["optimal"]
                if opt["reduction"] < 0:
                    problems.append(f"round {r['id']}: optimal reduction is negative")
    return problems


def cmd_check() -> int:
    if not OUT_PATH.exists():
        print(f"ERROR: {OUT_PATH} missing; run --refresh first.", file=sys.stderr)
        return 1
    data = json.loads(OUT_PATH.read_text(encoding="utf-8"))
    recomputed = build_data()
    if json.dumps(data, sort_keys=True) != json.dumps(recomputed, sort_keys=True):
        print("ERROR: committed artifact does not match a fresh recomputation.", file=sys.stderr)
        return 1
    problems = validate(data)
    if problems:
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1
    print(f"OK: {OUT_PATH.relative_to(REPO_ROOT)} is self-consistent.")
    _print_summary(data)
    return 0


def _print_summary(data: dict[str, Any]) -> None:
    for r in data["rounds"]:
        opt = r["optimal"]
        print(
            f"{r['id']:12s} n={len(r['activeObservationIds']):2d}  parentMSE={r['parentMSE']:7.3f}  "
            f"optimal={opt['feature']}<= {opt['threshold']:.2f}  reduction={opt['reduction']:7.3f}"
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--refresh", action="store_true", help="recompute and write the JSON artifact")
    mode.add_argument("--check", action="store_true", help="re-validate the committed JSON artifact (offline)")
    args = parser.parse_args(argv)
    return cmd_refresh() if args.refresh else cmd_check()


if __name__ == "__main__":
    raise SystemExit(main())
